#!/usr/bin/env python3
"""Generate the asap7 smem floorplan + macro placement TCL + preview PNG.

smem has 32 banks (NUM_BANKS=32) each instantiating one sram_1rw, which on
asap7 wraps a fakeram7_256x32 macro (8.36 x 42 um). Lay them out in an
8-col x 4-row grid with wide horizontal channels for the rd_out / wd_in
bus routing and a periphery margin for the bank mux + address decode
logic that surrounds the macros.

Outputs into tech/asap7/orfs/:
  - smem.macro_placement.tcl   (place_macro lines for ORFS)
  - smem.floorplan_preview.png (visual sanity check)
"""
from pathlib import Path
import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as patches
import matplotlib.pyplot as plt

REPO = Path(__file__).resolve().parents[4]
OUT_DIR = REPO / "tech/asap7/orfs"

NUM_BANKS = 32
COLS, ROWS = 8, 4

# smem_bank macro dimensions (from tech/asap7/orfs/smem_bank.config.mk
# DIE_AREA = 0 0 60 80). Wraps fakeram7_256x32 + per-output gating logic.
# Replaced the prior bare fakeram macros after the B1 refactor.
MACRO_W, MACRO_H = 60.0, 80.0

CH_X = 20.0   # horizontal channel between adjacent columns of macros
CH_Y = 20.0   # vertical channel between adjacent rows of macros
MARGIN = 40.0 # die-edge margin (periphery for OR-tree + decode + IO)


def main() -> None:
    block_w = COLS * MACRO_W + (COLS - 1) * CH_X
    block_h = ROWS * MACRO_H + (ROWS - 1) * CH_Y

    die_w = block_w + 2 * MARGIN
    die_h = block_h + 2 * MARGIN
    die_w = ((die_w // 50) + 1) * 50
    die_h = ((die_h // 50) + 1) * 50

    x0 = (die_w - block_w) / 2
    y0 = (die_h - block_h) / 2

    print(f"DIE: {die_w} x {die_h} um")
    print(f"Macros: {COLS} cols x {ROWS} rows = {NUM_BANKS}, "
          f"pitch x={MACRO_W+CH_X}, y={MACRO_H+CH_Y}")

    tcl = ["# Auto-generated by tech/asap7/orfs/scripts/gen_smem_floorplan.py",
           "# 32 fakeram7_256x32 macros in an 8x4 grid.", ""]
    placements = []
    for r in range(ROWS):
        for c in range(COLS):
            b = r * COLS + c
            x = x0 + c * (MACRO_W + CH_X)
            y = y0 + r * (MACRO_H + CH_Y)
            placements.append((b, x, y))
            tcl.append(
                f"place_macro -macro_name {{gen_banks\\[{b}\\].u_bank}} "
                f"-location {{{x:.3f} {y:.3f}}} -orientation R0"
            )
    tcl_path = OUT_DIR / "smem.macro_placement.tcl"
    tcl_path.write_text("\n".join(tcl) + "\n")
    print(f"\nWrote {tcl_path} ({NUM_BANKS} macros)")

    fig, ax = plt.subplots(figsize=(12, 12))
    ax.set_xlim(-die_w * 0.05, die_w * 1.05)
    ax.set_ylim(-die_h * 0.05, die_h * 1.05)
    ax.set_aspect("equal")
    ax.set_title(f"smem asap7 floorplan - {die_w:g} x {die_h:g} um")
    ax.set_xlabel("x (um)")
    ax.set_ylabel("y (um)")
    ax.add_patch(patches.Rectangle((0, 0), die_w, die_h, linewidth=2,
                                   edgecolor="black", facecolor="#fafafa"))
    for b, x, y in placements:
        ax.add_patch(patches.Rectangle((x, y), MACRO_W, MACRO_H,
                                       linewidth=0.5, edgecolor="#333",
                                       facecolor="#c7ecee", alpha=0.85))
        ax.text(x + MACRO_W / 2, y + MACRO_H / 2, f"{b}", ha="center",
                va="center", fontsize=7)
    # Margin annotation.
    ax.add_patch(patches.Rectangle((MARGIN/2, MARGIN/2),
                                   die_w - MARGIN, die_h - MARGIN,
                                   linewidth=1, edgecolor="#999",
                                   facecolor="none", linestyle="--"))
    ax.text(die_w / 2, MARGIN / 4, f"core margin {MARGIN/2:g} um",
            ha="center", va="center", fontsize=8, color="#666")
    png_path = OUT_DIR / "smem.floorplan_preview.png"
    fig.savefig(png_path, dpi=150, bbox_inches="tight")
    print(f"Wrote {png_path}")

    print(f"\nFor smem.config.mk:")
    print(f"  DIE_AREA  = 0 0 {die_w:g} {die_h:g}")
    print(f"  CORE_AREA = {MARGIN/2:g} {MARGIN/2:g} "
          f"{die_w - MARGIN/2:g} {die_h - MARGIN/2:g}")


if __name__ == "__main__":
    main()
