#!/usr/bin/env python3
"""Generate the 32×32 abutted compute_array floorplan + macro placement TCL
for issue #32 Phase C.

Outputs:
  tech/asap7/orfs/compute_array_abut.macro_placement.tcl

Layout:
  - cmd_unit (44.895 µm²) at SW corner (40, 40)
  - skew_lane_a column: 32 instances stacked on west edge of mac grid
  - skew_lane_b row: 32 instances along south edge of mac grid
  - 32×32 mac_tmem_cell_tile grid, ABUTTED (pitch = tile width exactly)

DIE math (printed at end): 1300×1300 µm. Paste DIE_AREA/CORE_AREA into
compute_array_abut.config.mk if you change ROWS/COLS or any geometry constant.
"""
from pathlib import Path

ROWS, COLS = 32, 32
TILE     = 34.56     # mac_tmem_cell_tile width = height (exact, abutment pitch)
SKEW_W   = 30.0      # skew_lane_a/b (square — grown in B6 for 260-bit chain register)
CMD      = 44.895    # cmd_unit (square)
EDGE     = 40.0      # die edge margin
GAP_CS   = 10.0      # cmd ↔ skew gap
GAP_MS   = 10.0      # skew ↔ mac-grid gap

REPO = Path(__file__).resolve().parents[4]
OUT  = REPO / "tech/asap7/orfs/compute_array_abut.macro_placement.tcl"

cmd_x, cmd_y = EDGE, EDGE
sa_x = cmd_x + CMD + GAP_CS
sb_y = cmd_y + CMD + GAP_CS
mac_x0 = sa_x + SKEW_W + GAP_MS
mac_y0 = sb_y + SKEW_W + GAP_MS
sa_y0, sb_x0 = mac_y0, mac_x0

mac_right = mac_x0 + COLS * TILE
mac_top   = mac_y0 + ROWS * TILE
die_w = ((mac_right + EDGE) // 50 + 1) * 50
die_h = ((mac_top   + EDGE) // 50 + 1) * 50

lines = [
    "# Auto-generated by tech/asap7/orfs/scripts/gen_compute_array_abut_floorplan.py",
    "# 32×32 abutted compute_array (issue #32 Phase C). Tiles abut with zero",
    "# inter-tile channel; skew_lane column + row and cmd_unit corner are placed",
    f"# with {GAP_CS}/{GAP_MS} µm channels around the perimeter.",
    "",
    f"place_macro -macro_name {{u_cmd}} -location {{{cmd_x} {cmd_y}}} -orientation R0",
]
for i in range(ROWS):
    lines.append(
        f"place_macro -macro_name {{gen_a_skew\\[{i}\\].u_a}} "
        f"-location {{{sa_x} {sa_y0 + i*TILE}}} -orientation R0"
    )
for j in range(COLS):
    lines.append(
        f"place_macro -macro_name {{gen_b_skew\\[{j}\\].u_b}} "
        f"-location {{{sb_x0 + j*TILE} {sb_y}}} -orientation R0"
    )
for i in range(ROWS):
    for j in range(COLS):
        lines.append(
            f"place_macro -macro_name {{gen_row\\[{i}\\].gen_col\\[{j}\\].u_cell}} "
            f"-location {{{mac_x0 + j*TILE} {mac_y0 + i*TILE}}} -orientation R0"
        )

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")

print(f"Wrote {OUT} ({len(lines)-5} macros)")
print(f"DIE: {die_w} x {die_h} µm")
print(f"Mac grid x=[{mac_x0:.3f}, {mac_right:.3f}], y=[{mac_y0:.3f}, {mac_top:.3f}]")
print(f"Set in compute_array_abut.config.mk: DIE_AREA = 0 0 {die_w} {die_h}")
