#!/usr/bin/env python3
"""Emit a useful-skew SDC for compute_array.

Reads a macro_placement.tcl, computes each macro's distance from a
designated "clock root" (cmd_unit by default), and emits one
set_clock_latency line per macro instance. Latency proportional to
distance so the clock front "follows" the data front outward from the
root, matching the systolic broadcast direction.

Usage:
    gen_useful_skew_sdc.py <placement_tcl> <out_sdc> [--root_inst u_cmd] [--ps_per_um 0.5]

Result is meant to be sourced FROM the design's main SDC, e.g.:
    source [file dirname [info script]]/compute_array_tiny.useful_skew.sdc
"""
import argparse
import math
import re
import sys
from pathlib import Path


def parse_placement(tcl_path: Path) -> dict[str, tuple[float, float]]:
    """Parse `place_macro -macro_name {NAME} -location {X Y} -orientation R0`.

    Returns {instance_name: (x, y)}. Instance names keep their escaped
    brackets from the TCL (e.g., 'gen_row\\[0\\].gen_col\\[0\\].u_cell').
    """
    pat = re.compile(
        r"place_macro\s+-macro_name\s+\{([^}]+)\}\s+-location\s+\{([\d.]+)\s+([\d.]+)\}"
    )
    out = {}
    for line in tcl_path.read_text().splitlines():
        m = pat.search(line)
        if m:
            name = m.group(1)
            x, y = float(m.group(2)), float(m.group(3))
            out[name] = (x, y)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("placement_tcl", type=Path)
    ap.add_argument("out_sdc", type=Path)
    ap.add_argument("--root_inst", default="u_cmd",
                    help="Instance name treated as clock-tree root (latency=0)")
    ap.add_argument("--ps_per_um", type=float, default=0.5,
                    help="Latency added per µm of Manhattan distance from root")
    args = ap.parse_args()

    placements = parse_placement(args.placement_tcl)
    if not placements:
        sys.exit(f"ERROR: no macros parsed from {args.placement_tcl}")
    if args.root_inst not in placements:
        sys.exit(f"ERROR: root instance {args.root_inst} not in placement "
                 f"(have: {list(placements)[:3]}...)")

    rx, ry = placements[args.root_inst]
    lines = [
        "# Auto-generated by tech/asap7/orfs/scripts/gen_useful_skew_sdc.py",
        f"# Root: {args.root_inst} @ ({rx}, {ry}) µm — latency 0",
        f"# Latency scale: {args.ps_per_um} ps per Manhattan-µm from root",
        "# Useful skew makes the clock front 'follow' the data front:",
        "# hold violations on outward data flow are satisfied by construction.",
        "",
    ]
    for name, (x, y) in sorted(placements.items()):
        dist = abs(x - rx) + abs(y - ry)
        latency_ps = dist * args.ps_per_um
        # ORFS uses ps for asap7 (lib time_unit). set_clock_latency takes
        # the lib's time unit. Use scientific-notation-free decimal.
        # TCL needs the escaped name in braces.
        # set_clock_latency syntax: [-source] [-max|-min] <delay> <object>.
        # Wrapped in `catch` because ORFS re-reads this SDC at every flow
        # stage (synth → fp → place → CTS). Pre-CTS, internal pins aren't
        # yet recognized as clock pins and the call errors. We only need
        # the constraint to take effect once CTS has propagated the clock.
        lines.append(
            f"catch {{ set_clock_latency -source -max {latency_ps:.3f} [get_pins {{{name}/clk}}] }}"
        )
        lines.append(
            f"catch {{ set_clock_latency -source -min {latency_ps:.3f} [get_pins {{{name}/clk}}] }}"
        )

    args.out_sdc.write_text("\n".join(lines) + "\n")
    print(f"Wrote {args.out_sdc}: {len(placements)} set_clock_latency lines")
    print(f"  Root: {args.root_inst} at ({rx}, {ry})")
    print(f"  Max latency: {max(abs(x-rx)+abs(y-ry) for x,y in placements.values()) * args.ps_per_um:.1f} ps")


if __name__ == "__main__":
    main()
