meta:
  version: 2
DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../../build/sv2v/chip_top.v
CLOCK_PORT: clk
CLOCK_PERIOD: 40
PL_TIME_DRIVEN: false
RUN_LINTER: false
SYNTH_STRATEGY: AREA 3
SYNTH_SHARE_RESOURCES: false
SYNTH_ABC_BUFFERING: false
SYNTH_HIERARCHY_MODE: keep
MACROS:
  sky130_sram_1kbyte_1rw1r_32x256_8:
    gds:
    - pdk_dir::libs.ref/sky130_sram_macros/gds/sky130_sram_1kbyte_1rw1r_32x256_8.gds
    lef:
    - pdk_dir::libs.ref/sky130_sram_macros/lef/sky130_sram_1kbyte_1rw1r_32x256_8.lef
    lib:
      '*':
      - pdk_dir::libs.ref/sky130_sram_macros/lib/sky130_sram_1kbyte_1rw1r_32x256_8_TT_1p8V_25C.lib
    instances:
      u_smem.gen_banks\[0\].u_sram.u_macro:
        location:
        - 50
        - 50
        orientation: N
      u_smem.gen_banks\[1\].u_sram.u_macro:
        location:
        - 520
        - 50
        orientation: N
      u_smem.gen_banks\[2\].u_sram.u_macro:
        location:
        - 990
        - 50
        orientation: N
      u_smem.gen_banks\[3\].u_sram.u_macro:
        location:
        - 1460
        - 50
        orientation: N
      u_smem.gen_banks\[4\].u_sram.u_macro:
        location:
        - 50
        - 750
        orientation: N
      u_smem.gen_banks\[5\].u_sram.u_macro:
        location:
        - 520
        - 750
        orientation: N
      u_smem.gen_banks\[6\].u_sram.u_macro:
        location:
        - 990
        - 750
        orientation: N
      u_smem.gen_banks\[7\].u_sram.u_macro:
        location:
        - 1460
        - 750
        orientation: N
      u_smem.gen_banks\[8\].u_sram.u_macro:
        location:
        - 50
        - 1450
        orientation: N
      u_smem.gen_banks\[9\].u_sram.u_macro:
        location:
        - 520
        - 1450
        orientation: N
      u_smem.gen_banks\[10\].u_sram.u_macro:
        location:
        - 990
        - 1450
        orientation: N
      u_smem.gen_banks\[11\].u_sram.u_macro:
        location:
        - 1460
        - 1450
        orientation: N
      u_smem.gen_banks\[12\].u_sram.u_macro:
        location:
        - 50
        - 2150
        orientation: N
      u_smem.gen_banks\[13\].u_sram.u_macro:
        location:
        - 520
        - 2150
        orientation: N
      u_smem.gen_banks\[14\].u_sram.u_macro:
        location:
        - 990
        - 2150
        orientation: N
      u_smem.gen_banks\[15\].u_sram.u_macro:
        location:
        - 1460
        - 2150
        orientation: N
      u_smem.gen_banks\[16\].u_sram.u_macro:
        location:
        - 50
        - 2850
        orientation: N
      u_smem.gen_banks\[17\].u_sram.u_macro:
        location:
        - 520
        - 2850
        orientation: N
      u_smem.gen_banks\[18\].u_sram.u_macro:
        location:
        - 990
        - 2850
        orientation: N
      u_smem.gen_banks\[19\].u_sram.u_macro:
        location:
        - 1460
        - 2850
        orientation: N
      u_smem.gen_banks\[20\].u_sram.u_macro:
        location:
        - 50
        - 3550
        orientation: N
      u_smem.gen_banks\[21\].u_sram.u_macro:
        location:
        - 520
        - 3550
        orientation: N
      u_smem.gen_banks\[22\].u_sram.u_macro:
        location:
        - 990
        - 3550
        orientation: N
      u_smem.gen_banks\[23\].u_sram.u_macro:
        location:
        - 1460
        - 3550
        orientation: N
      u_smem.gen_banks\[24\].u_sram.u_macro:
        location:
        - 50
        - 4250
        orientation: N
      u_smem.gen_banks\[25\].u_sram.u_macro:
        location:
        - 520
        - 4250
        orientation: N
      u_smem.gen_banks\[26\].u_sram.u_macro:
        location:
        - 990
        - 4250
        orientation: N
      u_smem.gen_banks\[27\].u_sram.u_macro:
        location:
        - 1460
        - 4250
        orientation: N
      u_smem.gen_banks\[28\].u_sram.u_macro:
        location:
        - 50
        - 4950
        orientation: N
      u_smem.gen_banks\[29\].u_sram.u_macro:
        location:
        - 520
        - 4950
        orientation: N
      u_smem.gen_banks\[30\].u_sram.u_macro:
        location:
        - 990
        - 4950
        orientation: N
      u_smem.gen_banks\[31\].u_sram.u_macro:
        location:
        - 1460
        - 4950
        orientation: N
FP_SIZING: absolute
DIE_AREA:
- 0
- 0
- 7000
- 7000
CORE_AREA:
- 50
- 50
- 6950
- 6950
