SIM            ?= verilator
TOPLEVEL_LANG  ?= verilog
VERILOG_SOURCES = $(PWD)/fp8_encode_tb_top.sv $(PWD)/../fp8_encode.sv
TOPLEVEL        = fp8_encode_tb_top
COCOTB_TEST_MODULES = test_fp8_encode

export PYTHONPATH := $(PWD)/../..:$(PYTHONPATH)
EXTRA_ARGS     += --trace --trace-structs

SIM_BUILD ?= sim_build_encode

include $(shell cocotb-config --makefiles)/Makefile.sim
