meta:
  version: 2
DESIGN_NAME: store
VERILOG_FILES:
- dir::../../../../build/sv2v/chip_top.v
CLOCK_PORT: clk
CLOCK_PERIOD: 40
RUN_LINTER: false
SYNTH_STRATEGY: AREA 3
SYNTH_SHARE_RESOURCES: false
SYNTH_ABC_BUFFERING: false
SYNTH_HIERARCHY_MODE: keep
PL_TIME_DRIVEN: false
FP_IO_HLAYER: met3 met5
FP_IO_VLAYER: met2 met4
FP_SIZING: absolute
DIE_AREA:
- 0
- 0
- 30000
- 30000
CORE_AREA:
- 50
- 50
- 29950
- 29950
